### ISSUE TITLE
map code

### ISSUE THREAD

**Issue by greglinch** [dajahenry/wp-content#2]
Because the map code is in a page and not GitHub, please reply here and share it using the Insert Code (<>) button.

<img width="432" alt="screen shot 2018-11-16 at 5 43 29 pm" src="https://user-images.githubusercontent.com/327783/48651077-331b7000-e9c7-11e8-93b0-199007149bb5.png">

**Comment by dajahenry** [comment]
`<h4> These are the countries I've traveled to so far. At each marker, there's the location and a photo. Click the name to enlarge the photo.</h4>

<center>

[leaflet-map height=500 width=750 lat=54.5 lng=15.2 zoom=2.2 zoomcontrol=1 align=center]

[leaflet-marker lat=44.4 lng=12.3] <a href="https://dajaehenry.files.wordpress.com/2018/04/img_5859.jpg?w=768&amp;h=512&amp;zoom=2">Venice, Italy</a>: <img src="https://dajaehenry.files.wordpress.com/2018/04/img_5859.jpg?w=7768&amp;h=5112&amp;zoom=2" alt="A bridge I crossed." />[/leaflet-marker]

[leaflet-marker lat=23.1 lng=-83.2] <a href="https://dajaehenry.files.wordpress.com/2018/04/img_9828.jpg?w=1250&amp;h=">Havana, Cuba</a>: <img src="https://dajaehenry.files.wordpress.com/2018/04/img_9828.jpg?w=1250&amp;h=" alt="A car." />[/leaflet-marker]

[leaflet-marker lat=50.85 lng=4.35] <a href="https://dajaehenry.files.wordpress.com/2018/11/img_5227.jpg?w=367&amp;h=245&amp;zoom=2">Brussels, Belgium </a>: <img src="https://dajaehenry.files.wordpress.com/2018/11/img_5227.jpg?w=367&amp;h=245&amp;zoom=2=" alt="A taste of Belgium." />[/leaflet-marker]

[leaflet-marker lat=52.97 lng=-9.42] <a href="https://dajaehenry.files.wordpress.com/2018/11/img_6148.jpg?w=367&amp;h=244&amp;zoom=2">Clare, Ireland </a>: <img src="https://dajaehenry.files.wordpress.com/2018/11/img_6148.jpg?w=367&amp;h=244&amp;zoom=2" alt="Cliffs of Moher." />[/leaflet-marker]

[leaflet-marker lat=35.76 lng=-5.83] <a href="https://dajaehenry.files.wordpress.com/2018/11/img_5629.jpg?w=831&amp;h=&amp;zoom=2">Tangier, Morocco </a>: <img src="https://dajaehenry.files.wordpress.com/2018/11/img_5629.jpg?w=831&amp;h=&amp;zoom=2" alt=" Hump day camel ride." />[/leaflet-marker]

[leaflet-marker lat=48.85 lng=2.3] <a href="https://dajaehenry.files.wordpress.com/2018/11/img_6317.jpg?w=369&amp;h=554&amp;zoom=2"> Paris, France </a>: <img src="https://dajaehenry.files.wordpress.com/2018/11/img_6317.jpg?w=369&amp;h=554&amp;zoom=2" alt=" The Eiffel Tower." />[/leaflet-marker]

[leaflet-marker lat=37.39 lng=-5.98] <a href="https://dajaehenry.files.wordpress.com/2018/11/img_4452.jpg?w=301&amp;h=201&amp;zoom=2"> Seville, Spain </a>: <img src="https://dajaehenry.files.wordpress.com/2018/11/img_4452.jpg?w=301&amp;h=201&amp;zoom=2" alt="Las Setas." />[/leaflet-marker]

[leaflet-marker lat=17.05 lng=-96.71] <a href="https://dajaehenry.files.wordpress.com/2018/11/20160716_151042.jpg?w=301&amp;h=169&amp;zoom=2"> Oaxaca, Mexico </a>: <img src="https://dajaehenry.files.wordpress.com/2018/11/20160716_151042.jpg?w=301&amp;h=169&amp;zoom=2" alt="Traditional wedding." />[/leaflet-marker]

[leaflet-marker lat=43.65 lng=-79.38] <a href="https://scontent-amt2-1.cdninstagram.com/vp/bece21982598374ec0c9113e35dfa68b/5C6EA444/t51.2885-15/e35/40238034_133804744233736_5679946406560845871_n.jpg"> Toronto, Ontario </a>: <img src="https://scontent-amt2-1.cdninstagram.com/vp/bece21982598374ec0c9113e35dfa68b/5C6EA444/t51.2885-15/e35/40238034_133804744233736_5679946406560845871_n.jpg" alt="Views." />[/leaflet-marker]

[leaflet-marker lat=38.72 lng=-9.14] <a href="https://scontent-amt2-1.cdninstagram.com/vp/5c4a771bd2f98b4bb79fd2275c67c99b/5C641057/t51.2885-15/e35/22794154_2064265160469747_3129466626752118784_n.jpg"> Lisbon, Portugal </a>: <img src="https://scontent-amt2-1.cdninstagram.com/vp/5c4a771bd2f98b4bb79fd2275c67c99b/5C641057/t51.2885-15/e35/22794154_2064265160469747_3129466626752118784_n.jpg" alt="Kayaking in Portugal." />[/leaflet-marker]

[juicer name="daja-henry"]

</center>`

**Comment by dajahenry** [comment]
The photo addresses and links included in the code showed up here as the actual photos and hyperlinks rather than code. I have attached screenshots.

![map code screenshot 2](https://user-images.githubusercontent.com/42515070/48675086-573f9400-eb22-11e8-8224-9a2c799def4d.JPG)
![map code screenshot](https://user-images.githubusercontent.com/42515070/48675087-573f9400-eb22-11e8-9268-35ed346b3b89.JPG)

**Comment by dajahenry** [comment]
The second photo should be first.

**Comment by greglinch** [comment]
@dajahenry Thank you!
