### ISSUE TITLE
fix map embed width

### ISSUE THREAD

**Issue by greglinch** [dajahenry/wp-content#7]
Remember that widths should generally be percentages. For example, 100% for this one:

<img width="400" alt="screen shot 2018-11-16 at 5 59 35 pm" src="https://user-images.githubusercontent.com/327783/48651572-7d9dec00-e9c9-11e8-87ae-5213729be78c.png">

Relatively minor given that the map is always just a segment of the globe, but you'll notice on the embed runs over and causes a horizontal scroll on smaller screens.

**Comment by dajahenry** [comment]
I edited the map width in CSS to make it 100%, but I can't tell if it made a difference. I don't know how to fix this issue.
