### ISSUE TITLE
consider removing bullets from navigation

### ISSUE THREAD

**Issue by greglinch** [dajahenry/wp-content#8]
The bullets appear when viewing on a phone-sized screen:

<img width="532" alt="screen shot 2018-11-16 at 5 58 23 pm" src="https://user-images.githubusercontent.com/327783/48652057-a58e4f00-e9cb-11e8-986f-43e596025f61.png">

**Comment by dajahenry** [comment]
Could not remove bullets, so I removed the sidebar menu widget. I think there is enough navigation already anyway.
